server:
  port: 8087

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: USER-CONSUMER
        uri: lb://USER-CONSUMER
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
