server:
  port: 8086

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: user-consumer
        uri: lb://USER-CONSUMER
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
