server:
  port: 8087

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: user-service
        uri:"http://user-consumer:8010"
        order: 0
        predicates:
          - Path=/customer/** 
        filters:
          - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
