server:
  port: 8087

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: user-service
        uri: lb://USER-CONSUMER
        order: 0
        predicates:
          - Path=/customer/**  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
